practica6/mi_aplicacion/urls.py
from django.urls import path
from . import views
from django.conf.urls import include

urlpatterns = [
  path('', views.index, name='index'),
  path('biblioteca', views.biblioteca, name='biblioteca'),
  path('biblioteca/libros', views.libros, name='libros'),
  path('biblioteca/libros/nuevo', views.libroNuevo, name='libroNuevo'),
  path('biblioteca/libros/eliminar', views.eliminarLibro, name='eliminarLibro'),
  path('biblioteca/libros/modificar/<int:pk>', views.modificarLibro, name='modificarLibro'),
  path('biblioteca/prestamos', views.prestamos, name='prestamos'),
  path('biblioteca/prestamos/nuevo/<int:pk>', views.prestarLibro, name='prestarLibro'),
  path('biblioteca/prestamos/cambiarEstado/<int:pk>/<str:estadoActual>', views.cambiarEstadoPrestamo, name='cambiarEstadoPrestamo'),
  path('biblioteca/prestamos/borrar/<int:pk>', views.borrarPrestamo, name='borrarPrestamo'),
  path('biblioteca/prestamos/modificar/<int:pk>', views.modificarPrestamo, name='modificarPrestamo'),
  path('biblioteca/usuarios', views.usuarios, name='usuarios'),
  path('biblioteca/usuarios/eliminar', views.eliminarUsuario, name='eliminarUsuario'),
  path('biblioteca/usuarios/modificar/<int:pk>', views.modificarUsuario, name='modificarUsuario'),
  path('biblioteca/autores', views.autores, name='autores'),
  path('biblioteca/autores/eliminar', views.eliminarAutor, name='eliminarAutor'),
]

#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

practica6/mi_sitio_web/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mi_aplicacion.urls')),
]

practica6/mi_aplicacion/models.py
# mi_aplicacion/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _
from datetime import date, timedelta, datetime
class Autor(models.Model):
    nombre      = models.CharField(max_length=200)
    apellidos   = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre + " " + self.apellidos
    class Meta:
        permissions = (("modificar_autor", "Añadir o eliminar autores"),)

class Libro(models.Model):
    isbn    = models.CharField(max_length=13, validators=[RegexValidator(regex='^.{13}$')])
    titulo  = models.CharField(max_length=200)
    autor   = models.ManyToManyField(Autor)
    imagen  = models.CharField(max_length=200)

    def __str__(self):
        return self.titulo
    class Meta:
        permissions = (("modificar_libros", "Añadir, modificar o eliminar autores"),)

class Usuario(models.Model):
    class Tipo(models.TextChoices):
        STAFF = "s", _("Personal de administración")
        CLIENTE = "c", _("Cliente de la biblioteca")

    dni         = models.CharField(max_length=9)
    nombre      = models.CharField(max_length=200)
    apellidos   = models.CharField(max_length=200)
    tipo        = models.CharField(max_length=1, choices=Tipo.choices, default=Tipo.CLIENTE)
    email       = models.EmailField(max_length=100)

    def __str__(self):
        return self.nombre + " " + self.apellidos
    class Meta:
        permissions = (("modificar_usuarios", "Añadir, modificar o eliminar usuarios"),)

class Prestamo(models.Model):
    class Estado(models.TextChoices):
        ACTIVO = "a", _("Activo")
        FINALIZADO = "f", _("Finalizado")

    fecha           = models.DateField(default=timezone.now)
    duracion_dias   = models.IntegerField(default=30)
    libro           = models.ForeignKey(Libro, on_delete=models.CASCADE)
    usuario         = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    estado          = models.CharField(max_length=2, choices=Estado.choices, default=Estado.ACTIVO)
    def fechaDevolucion(self):
        fechaDev = self.fecha  + timedelta(self.duracion_dias)
        return fechaDev
    def caducado(self):
        return self.fechaDevolucion() <= date.today()
    class Meta:
        permissions = (("modificar_prestamo", "Modificar, eliminar o cambiar el estado a un préstamo"),)

practica6/mi_aplicacion/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from mi_aplicacion.models import Libro, Autor, Prestamo, Usuario

class formAddLibro(forms.ModelForm):
    class Meta:
        model = Libro
        fields = ('isbn', 'titulo', 'autor', 'imagen')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Guardar libro'))
class formCrearAutor(forms.ModelForm):
    class Meta:
        model = Autor
        fields = ('nombre', 'apellidos')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Guardar autor'))

class formCrearUsuario(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = ('dni', 'nombre', 'apellidos', 'tipo', 'email')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Guardar usuario'))
    def dniReadonly(self):
        self.fields['dni'].widget.attrs["readonly"] = True

class formPrestamo(forms.ModelForm):
    class Meta:
        model = Prestamo
        fields = ('fecha', 'duracion_dias', 'usuario', 'libro', 'estado')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Guardar préstamo'))
    def setLibroInicial(self, pk):
        self.fields['libro'].initial = pk
    def paraClientes(self):
        self.fields["fecha"].widget.attrs["readonly"] = True
        self.fields["duracion_dias"].widget.attrs["readonly"] = True
        self.fields["estado"].widget.attrs["readonly"] = True
        self.fields.pop('usuario')

practica6/mi_aplicacion/views.py
from django.shortcuts import render, HttpResponse
from mi_aplicacion.models import Autor, Libro, Usuario, Prestamo
from mi_aplicacion.forms import formAddLibro, formCrearAutor, formCrearUsuario, formPrestamo
from django.http import HttpResponseRedirect, Http404
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User, Group
# Create your views here.

def index(request):
    return render(request,'base.html', {})

def biblioteca(request):
    context = {"var1": "variable número 1", "var2":"variable numero 2"}   # Aquí van la las variables para la plantilla
    return render(request,'base.html', context)

def libros(request):
    #se obtienen los libros almacenados
    libros = Libro.objects.all()
    context = {"libros":libros,
                "formAddLibro": formAddLibro}
    return render(request, 'libros.html', context)

@permission_required('mi_aplicacion.modificar_libros')
def libroNuevo(request):
    if request.method == "POST":
        form = formAddLibro(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Libro insertado correctamente')
        else:
            messages.add_message(request, messages.WARNING, 'No se ha modificado. Algún dato es erróneo.')
    else:
        raise Http404
    return HttpResponseRedirect("/biblioteca/libros")

@permission_required('mi_aplicacion.modificar_libros')
def eliminarLibro(request):
    if request.method == "POST":
        Libro.objects.filter(id=int(request.POST['id'])).delete()
        messages.add_message(request, messages.SUCCESS, 'Libro eliminado.')
        return HttpResponseRedirect("/biblioteca/libros")
    else:
        raise Http404

@permission_required('mi_aplicacion.modificar_libros')
def modificarLibro(request, pk):
    libro = Libro.objects.get(pk=pk)
    form = formAddLibro(instance=libro)
    if request.method == "POST":
        form = formAddLibro(request.POST, instance=libro)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Libro modificado correctamente')
        else:
            messages.add_message(request, messages.WARNING, 'No se ha modificado. Algún dato es erróneo.')

        return HttpResponseRedirect("/biblioteca/libros")
    else:

        context = {"formAddLibro": form}
        return render(request, 'modificarLibro.html', context)

@permission_required('mi_aplicacion.modificar_usuarios')
def usuarios(request):
    if request.method == "POST":
        form = formCrearUsuario(request.POST)
        if form.is_valid():
            form.save()
            #se inserta en la tabla usuarios de django
            user = User.objects.create_user(request.POST["dni"], request.POST["email"], request.POST["dni"]+"A")
            user.first_name = request.POST["nombre"]
            user.last_name = request.POST["apellidos"]
            user.save()
            if request.POST["tipo"] == "s":
                grupo = Group.objects.get(name="STAFF")
            else:
                grupo = Group.objects.get(name="CLIENTE")
            grupo.user_set.add(user)

    usuarios = Usuario.objects.all()
    context = {"usuarios":usuarios, "formCrearUsuario":formCrearUsuario}
    return render(request, 'usuarios.html', context)

@permission_required('mi_aplicacion.modificar_usuarios')
def eliminarUsuario(request):
    if request.method == "POST":
        usuarioBorrar = Usuario.objects.get(id=int(request.POST['id']))
        usuarioDjango = User.objects.get(username=usuarioBorrar.dni)
        usuarioDjango.delete()
        usuarioBorrar.delete()
        return HttpResponseRedirect("/biblioteca/usuarios")
    else:
        raise Http404

@permission_required('mi_aplicacion.modificar_usuarios')
def modificarUsuario(request, pk):
    usuario = Usuario.objects.get(pk=pk)

    if request.method == "POST":
        form = formCrearUsuario(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            #se modifica el grupo si fuera necesario
            user = User.objects.get(username=request.POST['dni'])
            grupoStaff = Group.objects.get(name="STAFF")
            grupoCliente = Group.objects.get(name="CLIENTE")
            user.groups.remove(grupoStaff)
            user.groups.remove(grupoCliente)
            if request.POST["tipo"] == "s":
                grupoStaff.user_set.add(user)
            else:
                grupoCliente.user_set.add(user)


            messages.add_message(request, messages.SUCCESS, 'Usuario modificado correctamente')
        else:
            messages.add_message(request, messages.WARNING, 'No se ha modificado. Algún dato es erróneo.')

        return HttpResponseRedirect("/biblioteca/usuarios")
    else:
        form = formCrearUsuario(instance=usuario)
        form.dniReadonly()
        context = {"formModUsuario": form}
        return render(request, 'modificarUsuario.html', context)

@permission_required('mi_aplicacion.modificar_autor')
def autores(request):
    if request.method == "POST":
        form = formCrearAutor(request.POST)
        if form.is_valid():
            form.save()
    autores = Autor.objects.all()
    context = {"autores":autores, "formCrearAutor":formCrearAutor}
    return render(request, 'autores.html', context)

@permission_required('mi_aplicacion.modificar_autor')
def eliminarAutor(request):
    if request.method == "POST":
        Autor.objects.filter(id=int(request.POST['id'])).delete()
        messages.add_message(request, messages.SUCCESS, 'Autor eliminado')
        return HttpResponseRedirect("/biblioteca/autores")
    else:
        raise Http404

@permission_required('mi_aplicacion.modificar_prestamo')
def prestamos(request):
    prestamos = Prestamo.objects.all().order_by('fecha')
    context = {"prestamos":prestamos}

    return render(request, 'prestamos.html', context)

@login_required
def prestarLibro(request, pk):
    if request.method == "POST":
        libroAPrestar = Prestamo.objects.filter(libro_id=int(request.POST["libro"])).filter(estado="a")
        #si está vacio es que no está prestado
        if not libroAPrestar.exists():


            if not request.user.has_perm('mi_aplicacion.modificar_prestamo'):
                usuarioLogado = Usuario.objects.get(dni=User.objects.get(username=request.user.username)).id
                post_values = request.POST.copy()
                post_values["usuario"] = usuarioLogado
                form = formPrestamo(post_values)
            else:
                form = formPrestamo(request.POST)
            if form.is_valid():
                form.save()
            else:
                messages.add_message(request, messages.ERROR,  str(form))
            messages.add_message(request, messages.SUCCESS, 'Libro prestado correctamente')
            return HttpResponseRedirect("/biblioteca/libros")
        else:
            messages.add_message(request, messages.WARNING, 'El libro se encuentra prestado actualmente')
            return HttpResponseRedirect("/biblioteca/libros")
    else:
        libroAPrestar = Prestamo.objects.filter(libro_id=int(pk)).filter(estado="a")
        #si está vacio es que no está prestado
        if not libroAPrestar.exists():
            form = formPrestamo()
            form.setLibroInicial(pk)
            if not request.user.has_perm('mi_aplicacion.modificar_prestamo'):
                #si el usuario no es staff no debe poder modificar el usuario, debe aparecer el suyo
                form.paraClientes()
            context = {"id":pk, "formPrestamo":form}
            return render(request, 'prestamoNuevo.html', context)
        else:
            messages.add_message(request, messages.WARNING, 'El libro se encuentra prestado actualmente')
            return HttpResponseRedirect("/biblioteca/libros")

@permission_required('mi_aplicacion.modificar_prestamo')
def cambiarEstadoPrestamo(request, pk, estadoActual):
    try:
        prestamo = Prestamo.objects.get(pk=pk)
        if estadoActual=="a":
            prestamo.estado = "f"
        elif estadoActual=="f":
            prestamo.estado = "a"
        prestamo.save()
        return HttpResponseRedirect("/biblioteca/prestamos")
    except ObjectDoesNotExist:
        messages.add_message(request, messages.WARNING, 'El préstamo ' + str(pk) + ' no existe')
        return HttpResponseRedirect("/biblioteca/prestamos")

@permission_required('mi_aplicacion.modificar_prestamo')
def borrarPrestamo(request, pk):
    try:
        Prestamo.objects.get(pk=pk).delete()
        messages.add_message(request, messages.SUCCESS, 'Borrado correcto')
        return HttpResponseRedirect("/biblioteca/prestamos")
    except ObjectDoesNotExist:
        messages.add_message(request, messages.WARNING, 'El préstamo ' + str(pk) + ' no existe')
        return HttpResponseRedirect("/biblioteca/prestamos")

@permission_required('mi_aplicacion.modificar_prestamo')
def modificarPrestamo(request, pk):
    prestamo = Prestamo.objects.get(pk=pk)

    if request.method == "POST":
        form = formPrestamo(request.POST, instance=prestamo)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Préstamo modificado correctamente')
        else:
            messages.add_message(request, messages.WARNING, 'No se ha modificado. Algún dato es erróneo.')

        return HttpResponseRedirect("/biblioteca/prestamos")
    else:
        form = formPrestamo(instance=prestamo)
        context = {"formModPrestamo": form}
        return render(request, 'modificarPrestamo.html', context)

practica6/mi_aplicacion/templates/autores.html
{%extends 'base.html'%}

{% if perms.mi_aplicacion.modificar_autor %}
  {% block colIzquierda %}
  <ul class="nav flex-column">
    <li class = "nav-item"><hr style="border-width: 5px;"></li>
    <li class = "nav-item text-center">
      <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#modalCrearAutor"><h4 class="nav-link">Añadir autor</h4></button>
    </li>
  </ul>
  {% endblock %}
{% endif %}


{% block contenido %}
<div class="container row text-center">
  {% for autor in autores %}
    <div class="card bg-light mb-1 mr-1" style="width: 12rem;">
      <h5 class="card-title text-center">{{autor}}</h5>
      <form method="post" action="{% url 'eliminarAutor'%}" onsubmit="return confirm('Vas a borrar al autor {{autor}}, estás seguro?')">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{autor.id}}">
        <button type="submit" class="btn"><i class="fas fa-trash"></i></button>
      </form>

    </div>
  {% endfor %}
</div>
<!--modal para añadir -->
<div class="modal fade" id="modalCrearAutor" tabindex="-1" role="dialog" aria-labelledby="tituloModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="tituloModal">Añadir autor</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body form-group text-center">
        <form method="post">
          {% load crispy_forms_tags %}
          {% crispy formCrearAutor %}
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>
{%endblock%}

practica6/mi_aplicacion/templates/libros.html
{% extends 'base.html' %}
{% block title %} Libros {% endblock %}


{% block colIzquierda %}
  {% if perms.mi_aplicacion.modificar_libros %}
  <ul class="nav flex-column">
    <li class = "nav-item"><hr style="border-width: 5px;"></li>
    <li class = "nav-item text-center">
      <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#modalAddLibro"><h4 class="nav-link">Añadir libro</h4></button>
    </li>
  </ul>
  {%else%}
  {{block.super}}
  {% endif %}

{% endblock %}

{% block contenido %}

  <div class="container row text-center">
    {% for libro in libros %}
      <div class="card bg-light mb-1 mr-1" style="width: 12rem;">
        <h5 class="card-title text-center">{{libro.titulo}}</h5>
        <img class="card-img" src="{{libro.imagen}}" alt="{{libro.titulo}}">
        <div class="card-body">
          <div class="collapse-content">
            <p class="card-text collapse  text-left" id="contenido-{{libro.id}}">
              <b>ISBN:</b> {{libro.isbn}}<br>
              <b>Autor/es:</b> {% for autor in libro.autor.all %}
                              {{autor.nombre}} {{autor.apellidos}}{% if not forloop.last %},{% endif %}
                            {% endfor %}
              <br>
            </p>
            <a class="btn  p-1 my-1 mr-0 mml-1 collapsed" data-toggle="collapse" href="#contenido-{{libro.id}}" aria-expanded="false" aria-controls="collapseContent"><i class="fas fa-info-circle"></i></a>
            <form method="post" action="{% url 'eliminarLibro'%}" onsubmit="return confirm('Vas a borrar el libro {{libro}}, estás seguro?')">
              {% csrf_token %}
              <input type="hidden" name="id" value="{{libro.id}}">
              {% if perms.mi_aplicacion.modificar_libros %}
              <button type="submit" class="btn"><i class="fas fa-trash"></i></button>
              <button type="button" class="btn" onclick="location.href='{% url 'modificarLibro' pk=libro.id %}';"><i class="fas fa-edit"></i></button>
              {% endif %}
              <button type="button" class="btn" onclick="location.href='{% url 'prestarLibro' pk=libro.id %}';"><i class="fas fa-handshake"></i></button>
            </form>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  <!--Ventanas modales-->
  <!--modal para añadir -->
  <div class="modal fade" id="modalAddLibro" tabindex="-1" role="dialog" aria-labelledby="tituloModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="tituloModal">Añadir libro</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body form-group text-center">
          <form method="post" action="{% url 'libroNuevo' %}">
            {% load crispy_forms_tags %}
            {% crispy formAddLibro %}
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
  </div>
{%endblock%}

practica6/mi_aplicacion/templates/modificarLibro.html
{% extends 'base.html' %}
{% block title %} Modificar libros {% endblock %}

{% block contenido %}
<div class="container">
  <form method="post">
    {% load crispy_forms_tags %}
    {% crispy formAddLibro %}
  </form>
</div>
{% endblock %}

practica6/mi_aplicacion/templates/modificarPrestamo.html
{% extends 'base.html' %}
{% block title %} Modificar préstamo {% endblock %}

{% block contenido %}
<div class="container">
  <form method="post">
    {% load crispy_forms_tags %}
    {% crispy formModPrestamo %}
  </form>
</div>
{% endblock %}

practica6/mi_aplicacion/templates/modificarUsuario.html
{% extends 'base.html' %}
{% block title %} Modificar usuario {% endblock %}

{% block contenido %}
<div class="container">
  <form method="post">
    {% load crispy_forms_tags %}
    {% crispy formModUsuario %}
  </form>
</div>
{% endblock %}

practica6/mi_aplicacion/templates/prestamoNuevo.html
{% extends 'base.html' %}
{% block title %} Prestamo nuevo {% endblock %}

{% block contenido %}
<div class="container">
  <form method="post">
    {% load crispy_forms_tags %}
    {% crispy formPrestamo %}
  </form>
</div>
{% endblock %}

practica6/mi_aplicacion/templates/prestamos.html
{% extends 'base.html'%}
{% block contenido %}
  <div class="container row text-center">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Libro</th>
          <th scope="col">Usuario</th>
          <th scope="col">Fecha</th>
          <th scope="col">Fecha de fin</th>
          <th scope="col">Estado</th>
          <th scope="col">Eliminar</th>
          <th scope="col">Modificar</th>
        </tr>
      </thead>
      <tbody>
        {% for prestamo in prestamos %}
          <tr {% if prestamo.estado == "f" %} class="bg-secondary" {% elif prestamo.caducado %} class="bg-danger" {% endif %}>
            <th scope="row">{{prestamo.id}}</th>
            <td>{{prestamo.libro}}</td>
            <td>{{prestamo.usuario}}</td>
            <td>{{prestamo.fecha | date:'d-m-y'}}</td>
            <td>{{prestamo.fechaDevolucion | date:'d-m-y'}}</td>
            <td><a href="{% url 'cambiarEstadoPrestamo' pk=prestamo.id estadoActual=prestamo.estado %}">{{prestamo.get_estado_display}}</td>
            <td><a href="{% url 'borrarPrestamo' pk=prestamo.id %}"><i class="fas fa-trash-alt"></i></td>
            <td><a href="{% url 'modificarPrestamo' pk=prestamo.id %}"><i class="fas fa-edit"></i></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

practica6/mi_aplicacion/templates/test.html
<div>Hola mundo</div>
<div>{{var1}}</div>
<div>{{var2}}</div>

practica6/mi_aplicacion/templates/usuarios.html
{%extends 'base.html'%}
{% block colIzquierda %}
<ul class="nav flex-column">
  <li class = "nav-item"><hr style="border-width: 5px;"></li>
  <li class = "nav-item text-center">
    <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#modalCrearUsuario"><h4 class="nav-link">Añadir usuario</h4></button>
  </li>
</ul>
{% endblock %}
{% block contenido %}
<div class="container row text-center">
  {% for usuario in usuarios %}
    <div class="card bg-light mb-1 mr-1" style="width: 12rem;">
      <h5 class="card-title text-center">{{usuario}}</h5>
      <div class="card-body">
        <div class="collapse-content">
          <p class="card-text collapse  text-left" id="contenido-{{usuario.id}}">
            <b>DNI:</b> {{usuario.dni}}<br>
            <b>Tipo:</b> {{usuario.get_tipo_display}}<br>
            <br>
          </p>
          <a class="btn  p-1 my-1 mr-0 mml-1 collapsed" data-toggle="collapse" href="#contenido-{{usuario.id}}" aria-expanded="false" aria-controls="collapseContent"><i class="fas fa-info-circle"></i></a>
          <form method="post" action="{% url 'eliminarUsuario'%}" onsubmit="return confirm('Vas a borrar al usuario {{usuario}}, estás seguro?')">
            {% csrf_token %}
            <input type="hidden" name="id" value="{{usuario.id}}">
            <button type="submit" class="btn"><i class="fas fa-trash"></i></button>
            <button type="button" class="btn" onclick="location.href='{% url 'modificarUsuario' pk=usuario.id %}';"><i class="fas fa-edit"></i></button>

          </form>
        </div>
      </div>

    </div>
  {% endfor %}
</div>
<!--modal para añadir -->
<div class="modal fade" id="modalCrearUsuario" tabindex="-1" role="dialog" aria-labelledby="tituloModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="tituloModal">Añadir usuario</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body form-group text-center">
        <form method="post">
          {% load crispy_forms_tags %}
          {% crispy formCrearUsuario %}
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>
{%endblock%}